[package]
name = "ritmo"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.77"
clap = { version = "4.5.26", features = ["derive"] }
futures-util = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sqlx = { version = "0.7.0", features = [ "runtime-tokio-rustls", "sqlite" ] } 
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
