[package]
name = "ritmo"
version = "1.0.0"
edition = "2021"
build = "build.rs" # Indica a Cargo di eseguire build.rs

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
csv = "1.3.1"
futures-util = "0.3.31"
once_cell = "1.20.2"
rayon = "1.10.0"
regex = "1.10.2"
serde = { version = "1.0.217", features = ["derive"] }
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sqlx = { version = "0.8.3", features = [ "runtime-tokio-rustls", "sqlite" ] } # o il database che usi
strsim = "0.11.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
unicode-normalization = "0.1.24"

[build-dependencies]
sea-orm-cli = { version = "0.12.15" }
