//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort: Option<String>,
    pub timestamp: Option<DateTimeUtc>,
    pub pubdate: Option<DateTimeUtc>,
    pub series_index: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub author_sort: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub isbn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lccn: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    pub flags: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub uuid: Option<String>,
    #[sea_orm(column_type = "custom(\"BOOL\")", nullable)]
    pub has_cover: Option<String>,
    pub last_modified: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
