//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "current_languages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub lang_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contents_current_languages::Entity")]
    ContentsCurrentLanguages,
}

impl Related<super::contents_current_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentsCurrentLanguages.def()
    }
}

impl Related<super::contents::Entity> for Entity {
    fn to() -> RelationDef {
        super::contents_current_languages::Relation::Contents.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::contents_current_languages::Relation::CurrentLanguages
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
