//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod aliases;
pub mod books;
pub mod books_contents;
pub mod books_people_roles;
pub mod books_tags;
pub mod contents;
pub mod contents_current_languages;
pub mod contents_original_languages;
pub mod contents_people_roles;
pub mod contents_source_languages;
pub mod contents_tags;
pub mod contents_types;
pub mod current_languages;
pub mod formats;
pub mod languages_names;
pub mod laverdure;
pub mod original_languages;
pub mod people;
pub mod publishers;
pub mod roles;
pub mod series;
pub mod source_languages;
pub mod tags;
