//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "people")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub nationality: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub birth_year: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::aliases::Entity")]
    Aliases,
    #[sea_orm(has_many = "super::books_people::Entity")]
    BooksPeople,
    #[sea_orm(has_many = "super::contents_people::Entity")]
    ContentsPeople,
}

impl Related<super::aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Aliases.def()
    }
}

impl Related<super::books_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksPeople.def()
    }
}

impl Related<super::contents_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentsPeople.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
