//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::aliases::Entity as Aliases;
pub use super::books::Entity as Books;
pub use super::books_contents::Entity as BooksContents;
pub use super::books_people_roles::Entity as BooksPeopleRoles;
pub use super::books_tags::Entity as BooksTags;
pub use super::contents::Entity as Contents;
pub use super::contents_current_languages::Entity as ContentsCurrentLanguages;
pub use super::contents_original_languages::Entity as ContentsOriginalLanguages;
pub use super::contents_people_roles::Entity as ContentsPeopleRoles;
pub use super::contents_source_languages::Entity as ContentsSourceLanguages;
pub use super::contents_tags::Entity as ContentsTags;
pub use super::contents_types::Entity as ContentsTypes;
pub use super::current_languages::Entity as CurrentLanguages;
pub use super::formats::Entity as Formats;
pub use super::languages_names::Entity as LanguagesNames;
pub use super::laverdure::Entity as Laverdure;
pub use super::original_languages::Entity as OriginalLanguages;
pub use super::people::Entity as People;
pub use super::publishers::Entity as Publishers;
pub use super::roles::Entity as Roles;
pub use super::series::Entity as Series;
pub use super::source_languages::Entity as SourceLanguages;
pub use super::tags::Entity as Tags;
