//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::books_people_roles::Entity")]
    BooksPeopleRoles,
    #[sea_orm(has_many = "super::contents_people_roles::Entity")]
    ContentsPeopleRoles,
}

impl Related<super::books_people_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksPeopleRoles.def()
    }
}

impl Related<super::contents_people_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentsPeopleRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
